before_deploy:
  - pip install --user awscli
  - echo 'this site was updated by travis with build id ${TRAVIS_BUILD_ID}' > ${TRAVIS_BUILD_DIR}/build.txt
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  skip_cleanup: true
  acl: public_read
  region: us-west-1
